
name: ${COMPOSE_PROJECT_NAME}

services:

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - '3000:3000'
    extra_hosts:
      # the default connection is set to yb:5433 so rederecting it to `ip_of_yugabytedb_database` defined in `.env` which default to `host-gateway`
      - yb:${ip_of_yugabytedb_database}
    user: "0:0"
    volumes:
      - .:/etc/grafanax:ro
      - .:/var/lib/grafana
    restart: unless-stopped

  dumpdb:
    # saves grafana.db to sql file when starting
    image: nouchka/sqlite3
    entrypoint: bash -xc 'sqlite3 /db/grafana.db .dump > /db/dump.grafana.db.sql'
    volumes:
      - .:/db


# example if you want to run a test cluster

  yugabytedb:
   image: yugabytedb/yugabyte:2024.1.0.0-b129
   command: |
    bash -xc ' 
     # try to join first node and if not (because it si the first node) try without --join
     yugabyted start \
      --tserver_flags="allowed_preview_flags_csv={ysql_yb_ash_enable_infra,ysql_yb_enable_ash},ysql_yb_ash_enable_infra=true,ysql_yb_enable_ash=true" \
      --background=false \
      --join ${COMPOSE_PROJECT_NAME}-yugabytedb-1 \
     || 
     yugabyted start \
      --tserver_flags="allowed_preview_flags_csv={ysql_yb_ash_enable_infra,ysql_yb_enable_ash},ysql_yb_ash_enable_infra=true,ysql_yb_enable_ash=true" \
      --background=false \
    '
   healthcheck:
    interval: 15s
    timeout: 3s
    test: postgres/bin/pg_isready -h $$(hostname)
   deploy:
    replicas: 0
    restart_policy: 
     condition: on-failure



