services:
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - '3000:3000'
    extra_hosts:
      - yb:${ip_of_yugabytedb_database}
    user: "0:0"
    volumes:
      - .:/etc/grafanax:ro
      - .:/var/lib/grafana
    restart: unless-stopped
