
name: ${COMPOSE_PROJECT_NAME}

services:

# example if you want to run a test cluster

  yugabytedb:
   image: yugabytedb/yugabyte:2024.1.0.0-b129
   command: |
    bash -xc ' 
     # try to join first node and if not (because it si the first node) try without --join
     yugabyted start \
      --tserver_flags="allowed_preview_flags_csv={ysql_yb_ash_enable_infra,ysql_yb_enable_ash},ysql_yb_ash_enable_infra=true,ysql_yb_enable_ash=true" \
      --background=false \
      --join ${COMPOSE_PROJECT_NAME}-yugabytedb-1 \
     || 
     yugabyted start \
      --tserver_flags="allowed_preview_flags_csv={ysql_yb_ash_enable_infra,ysql_yb_enable_ash},ysql_yb_ash_enable_infra=true,ysql_yb_enable_ash=true" \
      --ysql_enable_auth=true  --background=false \
    '
   healthcheck:
    interval: 15s
    timeout: 3s
    test: postgres/bin/pg_isready -h $$(hostname)
   deploy:
    replicas: 0
    restart_policy: 
     condition: on-failure



