{
 "title": "Active Session History",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "YugabyteDB Data Source", "query": "grafana-postgresql-datasource" },
   { "name": "agg", "label": "Aggregation", "query": "Host, Zone, Region, Cloud" },
   {
    "name": "server",
    "label": "Hosts",
    "query": "-- script to create the GV$ views though Foreign Data Wrapper\n-- It should not need the password as it uses current_user, but I didn't test it. \n\ndrop function if exists yb_ash_fdw;\ncreate function yb_ash_fdw(\n) returns table (\"__text\" text, \"__value\" text) as $PL$\n declare\n  ddl record;\n begin\n  execute 'create extension if not exists postgres_fdw';\n  execute 'drop foreign data wrapper if exists yb_ash_fdw cascade';\n  execute 'create foreign data wrapper yb_ash_fdw handler postgres_fdw_handler';\n  for ddl in (\n    select format('\n     create server if not exists \"gv$%1$s\"\n     foreign data wrapper yb_ash_fdw\n     options (host %2$L, port %3$L, dbname %4$L)\n     ', host, host, port, current_database()) as sql\n     from yb_servers()\n  ) loop\n   raise notice '(create server) SQL: %', ddl.sql ; execute ddl.sql;\n  end loop;\n  for ddl in (\n    select format('\n     create user mapping if not exists for current_user\n     server \"gv$%1$s\"\n     ',host) as sql\n     from yb_servers()\n  ) loop\n   raise notice '(create user mapping) SQL: %', ddl.sql ; execute ddl.sql;\n  end loop;\n  for ddl in (\n    select format('\n     drop schema if exists \"gv$%1$s\" cascade\n     ',host) as sql\n     from yb_servers()\n  ) loop\n   raise notice '(drop schema) SQL: %', ddl.sql ; execute ddl.sql;\n  end loop;\n  for ddl in (\n    select format('\n     create schema if not exists \"gv$%1$s\"\n     ',host) as sql\n     from yb_servers()\n  ) loop\n   raise notice '(create schema) SQL: %', ddl.sql ; execute ddl.sql;\n  end loop;\n  for ddl in (\n    select format('\n     import foreign schema \"pg_catalog\"\n     limit to (\"yb_active_session_history\",\"pg_stat_statements\",\"yb_local_tablets\")\n     from server \"gv$%1$s\" into \"gv$%1$s\"\n     ', host) as sql from yb_servers()\n  ) loop\n   raise notice '(import foreign schema) SQL: %', ddl.sql ; execute ddl.sql;\n  end loop;\n  for ddl in (\n    with views as (\n    select distinct foreign_table_name\n    from information_schema.foreign_tables t, yb_servers() s\n    where foreign_table_schema = format('gv$%1$s',s.host)\n    )\n    select format('create view public.\"gv$%2$s\" as %1$s',\n     string_agg(\n     format('\n     select %2$L as gv$host, %3$L as gv$zone, %4$L as gv$region, %5$L as gv$cloud,\n     * from \"gv$%2$s\".%1$I\n     ', foreign_table_name, host, zone, region, cloud)\n     ,' union all '), foreign_table_name\n    ) as sql from views, yb_servers() group by views.foreign_table_name\n  ) loop\n   raise notice '(create views) SQL: %', ddl.sql ; execute ddl.sql;\n  end loop;\n  return query \nselect distinct format('%s.%s.%s %s',gv$cloud,gv$region,gv$zone,gv$host) as \"__text\" , gv$host as \"__value\"\nfrom gv$yb_active_session_history  where '$agg'='Host'\nunion all\nselect distinct format('%s.%s.%s',gv$cloud,gv$region,gv$zone,gv$host) as \"__text\" , gv$zone as \"__value\"\nfrom gv$yb_active_session_history where '$agg'='Zone'\nunion all\nselect distinct format('%s.%s',gv$cloud,gv$region,gv$zone,gv$host) as \"__text\" , gv$region as \"__value\"\nfrom gv$yb_active_session_history where '$agg'='Region'\nunion all\nselect distinct format('%s',gv$cloud,gv$region,gv$zone,gv$host) as \"__text\" , gv$cloud as \"__value\"\nfrom gv$yb_active_session_history where '$agg'='Cloud'\n;\n end;\n$PL$ language plpgsql;\n\n\n\nselect \"__text\", \"__value\" from yb_ash_fdw() \n;\n"
   },
   {
    "name": "component",
    "label": "ASH",
    "query": "select distinct wait_event_component from gv$yb_active_session_history"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Session History - $server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "server"
  },
  {
   "title": "Wait Event - $component - $server",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "repeat": "component",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\r\nsample_time::timestamp as \"time\"\r\n,format('%s %s %s:%s',wait_event_component,wait_event_class,wait_event_type,wait_event)\r\n, sum(sample_weight) as \"AAS\"\r\nfrom gv$yb_active_session_history\r\nwhere sample_time between $__timeFrom() and $__timeTo()\r\nAnd wait_event_component in ($component)\r\nand (\r\n  gv$host in ($server) or gv$zone in ($server) or gv$region in ($server) or gv$cloud in ($server) \r\n)\r\ngroup by\r\nsample_time,wait_event_component,wait_event_type ,wait_event_class,wait_event\r\norder by sample_time,sum(sample_weight) ,\r\nwait_event_component,wait_event_type,wait_event_class,wait_event\r\n;"
    }
   ]
  },
  { "title": "Statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Statements - $component",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 31 },
   "repeat": "component",
   "targets": [
    {
     "rawSql": "select\r\nsample_time::timestamp as \"time\"\r\n,format('/* %s */ %s',query_id,coalesce(query,\r\ncase query_id -- https://github.com/yugabyte/yugabyte-db/blob/d040fd81ea14e83c08300daf5e2f0c7a0eab42de/src/yb/ash/wait_state.h#L195\r\nwhen 1 then '-- background: kQueryIdForLogAppender'\r\nwhen 2 then '-- background: kQueryIdForFlush'\r\nwhen 3 then '-- background: kQueryIdForCompaction'\r\nwhen 4 then '-- background: kQueryIdForRaftUpdateConsensus'\r\nwhen 5 then '-- background: kQueryIdForCatalogRequests'\r\nwhen 6 then '-- background: kQueryIdForLogBackgroundSync'\r\nend,' -- not in pg_stat_statements'))\r\n, sum(sample_weight) as \" \"\r\nfrom gv$yb_active_session_history\r\nleft outer join (select queryid as query_id, gv$host,query, calls, rows, total_time from gv$pg_stat_statements) stmts \r\nusing (gv$host, query_id)\r\nwhere sample_time between $__timeFrom() and $__timeTo()\r\nAnd wait_event_component in ($component)\r\nand (\r\n  gv$host in ($server) or gv$zone in ($server) or gv$region in ($server) or gv$cloud in ($server) \r\n)group by\r\nsample_time,query_id,query\r\norder by sample_time,sum(sample_weight) ,\r\nquery_id\r\n;"
    }
   ]
  },
  { "title": "Tablets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Tablets - $server",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
   "repeat": "server",
   "targets": [
    {
     "rawSql": "select\r\nsample_time::timestamp as \"time\"\r\n,format('%s.%s %s.%s [%s,%s] %s',table_type, namespace_name, ysql_schema_name, table_name, partition_key_start, partition_key_end, tablet_id)\r\n, sum(sample_weight) as \" \"\r\nfrom gv$yb_active_session_history\r\njoin (select substr(tablet_id,1,15) as wait_event_aux, gv$host, table_id, table_type, namespace_name, ysql_schema_name, table_name, partition_key_start, partition_key_end, tablet_id from gv$yb_local_tablets) stmts\r\nusing (gv$host, wait_event_aux)\r\nwhere sample_time between $__timeFrom() and $__timeTo()\r\nAnd wait_event_component in ($component)\r\nand (\r\n  gv$host in ($server) or gv$zone in ($server) or gv$region in ($server) or gv$cloud in ($server)\r\n)\r\ngroup by\r\nsample_time,table_id,table_type, namespace_name, ysql_schema_name, table_name, partition_key_start, partition_key_end, tablet_id\r\norder by sample_time,sum(sample_weight) ,\r\ntable_id\r\n;\r\n"
    }
   ]
  },
  {
   "title": "Tablets - $server",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "rawSql": "select\r\nsample_time::timestamp as \"time\"\r\n,format('%s.%s %s.%s [%s,%s] %s %s',table_type, namespace_name, ysql_schema_name, table_name, partition_key_start, partition_key_end, wait_event_aux, gv$host)\r\n, sum(sample_weight) as \" \"\r\nfrom gv$yb_active_session_history\r\njoin (select substr(tablet_id,1,15) as wait_event_aux, gv$host, table_id, table_type, namespace_name, ysql_schema_name, table_name, partition_key_start, partition_key_end, tablet_id from gv$yb_local_tablets) stmts\r\nusing (gv$host, wait_event_aux)\r\nwhere sample_time between $__timeFrom() and $__timeTo()\r\nAnd wait_event_component in ($component)\r\nand (\r\n  gv$host in ($server) or gv$zone in ($server) or gv$region in ($server) or gv$cloud in ($server)\r\n)\r\ngroup by\r\nsample_time,table_id,table_type, namespace_name, ysql_schema_name, table_name, partition_key_start, partition_key_end, wait_event_aux, gv$host\r\n--having sum(sample_weight)>=1\r\norder by sample_time,sum(sample_weight) , table_id\r\n;\r\n"
    }
   ]
  }
 ]
}